rm -rf SAMFileReader_fse_compress_multi SAMFileReader_fse_compress_single SAMFileReader_fse_decompress_multi SAMFileReader_fse_decompress_single SAMFileReader_gzip_compress_multi SAMFileReader_gzip_compress_single SAMFileReader_gzip_decompress_multi  SAMFileReader_gzip_decompress_single SAMFileReader_zstd_compress_multi SAMFileReader_zstd_compress_single SAMFileReader_zstd_decompress_multi SAMFileReader_zstd_decompress_single
make clean
bash cleaner.sh
